# Generated by Django 5.0.2 on 2024-02-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_model',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
