# Generated by Django 5.0.2 on 2024-02-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_model_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_model',
            name='phone',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
