# Generated by Django 4.2.1 on 2024-08-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contact_model_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('details', models.TextField(blank=True, max_length=500, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('skill', models.TextField(blank=True, null=True)),
                ('hobby', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='profile/default.png', null=True, upload_to='')),
            ],
        ),
    ]
