# Generated by Django 4.2.1 on 2024-08-12 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_aboutmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_model',
            name='user',
        ),
    ]
