# Generated by Django 4.2.1 on 2024-08-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_remove_contact_model_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_model',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
