# Generated by Django 4.2.1 on 2024-08-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_contact_model_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_model',
            name='text',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
