# Generated by Django 4.2.1 on 2024-08-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_rename_recipients_message_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_update',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile_update',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile_update',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
