# Generated by Django 4.2.1 on 2024-08-13 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0008_profile_update_email_profile_update_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_update',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile_update',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile_update',
            name='last_name',
        ),
    ]
