# Generated by Django 4.2.1 on 2024-08-14 16:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0010_notification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='NotificationModel',
        ),
    ]
