# Generated by Django 5.0.2 on 2024-02-14 15:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='To_do_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveIntegerField(blank=True, null=True)),
                ('work_time', models.TimeField(blank=True, null=True)),
                ('work_name', models.CharField(blank=True, max_length=100, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
