# Generated by Django 5.0.2 on 2024-02-16 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='to_do_list',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='to_do_list',
            name='serial_number',
        ),
    ]
