# Generated by Django 5.0.2 on 2024-03-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_to_do_list_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_do_list',
            name='done_count',
            field=models.IntegerField(default=0),
        ),
    ]
