# Generated by Django 5.0.2 on 2024-03-01 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_to_do_list_done_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='to_do_list',
            name='done_count',
        ),
        migrations.CreateModel(
            name='Success_day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done_count', models.IntegerField(default=0)),
                ('percentage_score', models.FloatField(null=True)),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='success', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
