# Generated by Django 5.0.2 on 2024-03-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_to_do_list_done_count_success_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='success_day',
            name='done_count',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
