# Generated by Django 5.0.2 on 2024-03-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_success_day_done_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_do_list',
            name='done_bol',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='success_day',
            name='done_count',
            field=models.IntegerField(default=0),
        ),
    ]
