# Generated by Django 4.2.1 on 2024-08-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_to_do_list_done_bol_alter_success_day_done_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_list',
            name='done_bol',
            field=models.BooleanField(default=False),
        ),
    ]
